ConsenSys/doc.ethsigner

- mkdocs.yml
Reverts PegaSysEng/doc.ethsigner#3
> Revert "fix repos url"

- docs/Extending-EthSigner/Adding-Signer.md
- docs/Installation/Build-From-Source.md
- docs/Installation/Install-Binaries.md
- docs/Reference/EthSigner-CLI.md
- docs/Using-EthSigner/Azure.md
- docs/Using-EthSigner/Getting-Started.md
- docs/Using-EthSigner/Hashicorp.md
- docs/Using-EthSigner/Using-EthSigner.md
- docs/index.md
- mkdocs.yml
update with original doc latest changes from PRs that were merged after extracting the doc (https://github.com/PegaSysEng/ethsigner/pull/122).
> update with original doc latest changes

- docs/Using-EthSigner/Using-EthSigner.md
Updated for eeaSendTransaction nonce being required
> Updated for eeaSendTransaction nonce being required

- .circleci/config.yml
update to v2.1 of ci; use docker executors
update to v2.1 of ci; use docker executors
> updating ci version and using docker executors

- .circleci/config.yml
will take steps failure in account as we can make them optional in github using the "required"checkbox in branch settings
no ticket
> Take steps failure in account as we can make them optional in github

- .circleci/config.yml
add option to exclude localhost links checks as localhost services are usually not available as they are examples in the doc.
> add option to exclude localhost links checks

- docs/Security/Responsible-Disclosure.md
- mkdocs.yml
Add Security Disclosure Policy to the Ethsigner documentation.
PAN-2994
> [PAN-2994] Add responsible disclosure policy.

- .circleci/config.yml
- .gitignore
- CONTRIBUTING.md
- DOC-STYLE-GUIDE.md
- GOVERNANCE.md
- MKDOCS-MARKDOWN-GUIDE.md
- link_check_conf.json
- package-lock.json
- package.json
port the changes made to doc.pantheon CI for link checker
fixes ethsigner part of https://pegasys1.atlassian.net/browse/PIE-1897
> port the changes made to doc.pantheon CI for link checker

- docs/index.md
> Fix casing

- docs/Using-EthSigner/Azure.md
- docs/Using-EthSigner/Getting-Started.md
- docs/Using-EthSigner/Hashicorp.md
- docs/Using-EthSigner/Using-EthSigner.md
Update all instances of Pantheon to Besu.
ES-46
> [ES-46] Update Pantheon to Besu.

- .circleci/config.yml
adding a nightly cron for linkchecker
> adding a nightly cron for linkchecker

- docs/Concepts/Multiple-Key-Files.md
- docs/HowTo/Extending-EthSigner/Add-Signer.md
- docs/HowTo/Get-Started/Build-From-Source.md
- docs/HowTo/Get-Started/Install-Binaries.md
- docs/HowTo/Get-Started/Use-Docker.md
- docs/HowTo/Store-Keys/Use-Azure.md
- docs/HowTo/Store-Keys/Use-Hashicorp.md
- docs/HowTo/Transactions/Make-Transactions.md
- docs/Reference/CLI/CLI-Syntax.md
- docs/Reference/Responsible-Disclosure.md
- docs/Tutorials/Multifile.md
- docs/Tutorials/Start-EthSigner.md
- mkdocs.yml
Signed-off-by: Steven Gregg <steven.gregg@consensys.net>
Change headline-style to sentence-style in our headings
PIE-2154
> [PIE-2154] Change headings to sentence-style

- docs/HowTo/Extending-EthSigner/Add-Signer.md
Signed-off-by: Steven Gregg <steven.gregg@consensys.net>
Change complex words
PIE-2154
> [PIE-2154] Simplify complex words

- docs/HowTo/Get-Started/Use-Docker.md
Signed-off-by: Steven Gregg <steven.gregg@consensys.net>
Remove forms of to be.
PIE-2154
> [PIE-2154] Remove forms of to be

- docs/Reference/Multikey-Parameters.md
Add relative and absolute path information.
ES-83
> [ES-83] Add relative and absolute path information.

- docs/HowTo/Transactions/Make-Transactions.md
- docs/Reference/CLI/CLI-Syntax.md
Rules changes and log level changes to match our guidelines.
Fixes PAN-2515
> Update vale rules

- .circleci/config.yml
build failure notifications with orbs
> build failure notifications with orbs

- mkdocs.yml
Redirects will be handled at the code level and not in the RTD admin interface. So they will be versioned, easy to reverse, be part of the review process.
fixes IT-264
> Add in-code redirect management

- docs/HowTo/Use-Multiple-Signers.md
fix description copy paste mistake that was indicating
fixes #58
> fix description copy paste mistake

- docs/Reference/Responsible-Disclosure.md
update common submodule.
Fixes an edit button issue that is the cause for PegaSysEng/Misc#40
> update common submodule

- docs/HowTo/Store-Keys/Use-Hashicorp.md
- mkdocs.yml
Fixing Hashicorp tutorial to not use TLS
> Fixing Hashicorp tutorial to not use TLS

- docs/Reference/CLI/CLI-Syntax.md
- docs/Tutorials/Multifile.md
- docs/Tutorials/Start-EthSigner.md
Document the `--downstream-http-path` option.
> Document the --downstream-http-path option.

- docs/Reference/API-Methods.md
> Add eth_sign API.

- docs/Reference/CLI/CLI-Syntax.md
Add CORS validation CLI option.
> Add CORS validation CLI option.

- .gitmodules
- mkdocs.yml
Update submodule for text logo handling (removes the duplicate site title on top left)
> update submodule and text logo handling

- mkdocs.yml
> Consensys update

- docs/HowTo/Transactions/Make-Transactions.md
- docs/Reference/API-Methods.md
- docs/index.md
> Update for Quorum

- docs/HowTo/Get-Started/Use-Docker.md
- docs/HowTo/Use-Configuration-File.md
- docs/Reference/CLI/CLI-Subcommands.md
- docs/Reference/CLI/CLI-Syntax.md
- mkdocs.yml
Add configuration file and environment variables.
Additionally updated the Docker instructions to show an example using the env variables.
> Add configuration file and environment variables.

- .circleci/config.yml
- .markdownlintignore
- README.md
- docs/Concepts/Overview.md
- docs/Concepts/TLS.md
- docs/HowTo/Extending-EthSigner/Add-Signer.md
- docs/HowTo/Store-Keys/Use-Hashicorp.md
- docs/HowTo/Use-Multiple-Signers.md
- docs/HowTo/Use-Single-Signer.md
- docs/Reference/CLI/CLI-Subcommands.md
- docs/Reference/CLI/CLI-Syntax.md
- docs/Reference/Multikey-Parameters.md
- docs/Reference/Responsible-Disclosure.md
- docs/Tutorials/Multifile.md
- docs/Tutorials/Start-EthSigner.md
- Update submodule and config to use new Vale2 guidelines checking tool.
- fix errors raised by this new version
see PegaSysEng/Misc#29
> Update to Vale2

- docs/Reference/CLI/CLI-Subcommands.md
- docs/Reference/Multikey-Parameters.md
Add tenant ID parameter for Azure.
> Add tenant ID parameter for Azure.

- .circleci/config.yml
> adding docker contexts

- docs/Tutorials/Quorum-Dev-Quickstart.md
- docs/index.md
- mkdocs.yml
Added section linking to quickstart to homepage
> Added quickstart

- docs/HowTo/Store-Keys/Use-Azure.md
- docs/HowTo/Store-Keys/Use-Hashicorp.md
- docs/Tutorials/Multifile.md
- docs/Tutorials/Start-EthSigner.md
Signed-off-by: Sally MacFarlane <sally.macfarlane@consensys.net>
Use updated besu CLI option
> [MINOR] use host-allowlist on besu cmd line

- docs/HowTo/Extending-EthSigner/Add-Signer.md
- docs/HowTo/Get-Started/Build-From-Source.md
- docs/Reference/API-Methods.md
- docs/Reference/Responsible-Disclosure.md
- docs/Tutorials/Multifile.md
Updated links and email
Fixes #100
> Updated links and email address to ConsenSys

- docs/HowTo/Get-Started/Install-Binaries.md
Update latest packaged binaries link to cloudsmith
> Update latest packaged binaries link to cloudsmith

- docs/HowTo/Get-Started/Build-From-Source.md
- docs/HowTo/Get-Started/Install-Binaries.md
> Fix JDK download page link

- docs/Reference/API-Methods.md
Add documentation for eth_signTransaction endpoint.
fixes #99
> doc add eth_signTransaction endpoint

- docs/HowTo/Monitor-Nodes/Metrics.md
- docs/Reference/CLI/CLI-Syntax.md
- mkdocs.yml
Signed-off-by: bgravenorst <byron.gravenorst@consensys.net>
Added instructions to configure monitoring for EthSigner.
Fixes #92
> Document how to monitor EthSigner.

- docs/HowTo/Use-Single-Signer.md
Use the following list to make sure your PR fits the EthSigner doc quality standard.
> subcommand links fixed

- docs/Reference/CLI/CLI-Subcommands.md
- docs/Reference/CLI/CLI-Syntax.md
Use the following list to make sure your PR fits the EthSigner doc quality standard.
fixes #116
> typos (116)

- docs/HowTo/Get-Started/Build-From-Source.md
- docs/HowTo/Transactions/Make-Transactions.md
- docs/HowTo/Use-Multiple-Signers.md
- docs/HowTo/Use-Single-Signer.md
- docs/Reference/API-Methods.md
- docs/Reference/CLI/CLI-Subcommands.md
- docs/Reference/CLI/CLI-Syntax.md
- docs/Reference/Multikey-Parameters.md
- docs/Tutorials/Multifile.md
- docs/Tutorials/Start-EthSigner.md
- docs/index.md
- mkdocs.yml
Use the following list to make sure your PR fits the EthSigner doc quality standard.
Update headers to sentence case.
Fixes #122
> Update headers to sentence case

- docs/HowTo/Get-Started/Use-Docker.md
Updated docker hub links from pegasyseng to consensys.
fixes #127 
- Open https://docs.ethsigner.consensys.net/en/stable/HowTo/Get-Started/Use-Docker/
- Check that we are referring to https://hub.docker.com/r/consensys/ethsigner
> Update docker hub links (from pegasyseng to consensys)

- docs/HowTo/Transactions/Make-Transactions.md
- docs/Reference/API-Methods.md
Use the following list to make sure your PR fits the EthSigner doc quality standard.
update to new goquorum doc
outdated url, see https://app.circleci.com/pipelines/github/ConsenSys/doc.ethsigner/1008/workflows/93659304-0d3b-4a82-8394-f80887d0a050/jobs/1972
> update to new goquorum doc

- docs/Reference/Multikey-Parameters.md
Use the following template to make sure your PR fits the EthSigner documentation standard.
Update Hashicorp multikey configuration parameters and example.
For content changes:
For tool changes:
and added a [preview link](#preview).
https://pegasys-ethsigner--134.com.readthedocs.build/en/134/Reference/Multikey-Parameters/#hashicorp-vault-signing
> Hashicorp multikey

- .github/ISSUE_TEMPLATE/content_issue.md
- .github/ISSUE_TEMPLATE/tool_issue.md
- README.md
- mkdocs.extra.yml
Use the following template to make sure your PR fits the ConsenSys documentation standard.
Updated the name of project to EthSigner in some files.
Note: this is the first PR on the migrated doc, so also trying that everything works well.
- Some remains of copy/paste to update to the right project name
- Version dropdown not activated
For content changes:
For tool changes:
> Migration finish

- docs/HowTo/Use-Multiple-Signers.md
Use the following template to make sure your PR fits the ConsenSys documentation standard.
Update documentation on the toml file to mention that is must be lowercase.
For content changes:
For tool changes:
> Mention that the multikey toml file be in lowercase.

- docs/HowTo/Metrics.md
- docs/HowTo/Store-Keys/Use-Hashicorp.md
- docs/Reference/CLI/CLI-Subcommands.md
- docs/Tutorials/Multifile.md
Made minor fixes to the documentation.
> docs: fix minor issues

- docs/support.md
- docusaurus.config.js
update discord links to custom consensys link.
> update discord links
